
#ABOUT SYNTAX ERRORS AND EXCEPTIONS

''' 
- Syntax errors - errors that may be commited inadvertently by the user while writin the code;
- example: spelling a keyword wrong, not indenting the code and so on.

- An exception on the other hand is an error that occurs during program execution. A user may enter
- incorrect data while running the program. If you want to divide a number ('a') with another number ('b')
- but give a value of 0 to the denominator ('b'), this will generate an exception.

- The exceptions, which are autogenerated in Python and displayed to the user, may not lucidly convey the problem.
- Using exception handling with the try-except construct, we can frame a user-friendly message to enable the user 
- to better correct the error.

- There are two parts to exception handling. First, we put the code that is likely to cause an error under a try clause.
- Then in the except clause, we try to deal with whatever caused an error in the try block. We mention the name of the
- exception class in the except clause, followed by a code block where we handle the error.
- A straightforward method for handling the error is printing a message that gives the user more details on what they need to correct.

- A simple example of a program, with and without exception handling is shown below:

    #CODE

    while True:
        try:
            n=int(input("Enter your score:"))
            print("You obtained a score of ", n)
            break
        except ValueError:
            print("Enter only an integer value")
    
    #OUTPUT

    Enter your score(Without a decimal point):abc
    Enter only an integer value
    Enter your score(Without a decimal point): 45.5
    Enter only an integer value
    Enter your score(Without a decimal point): 90
    You obtained a score of 90

- Same program (without exception handling)

    #CODE

    n=int(input("Enter your score:"))
    print("You obtained a score of ", n)

    #OUTPUT

    Enter your score: ninety three

    ValueError  ...



'''